#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults single
PROCESS_NAME="unbound"

check_container_initialized
check_service_initialized init
liftoff

print_start "Starting Unbound $(echo "${UNBOUND_VERSION}" | sed 's|release||g')"
exec unbound -c "${CONFIG_PATH}""${CONFIG_FILE}" -d
