#!/usr/bin/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/03-monitoring
prepare_service single
PROCESS_NAME="unbound"

configure_logging
create_configuration
setup_monitoring

liftoff
