#!/command/with-contenv bash

source /assets/functions/00-container

prepare_service
PROCESS_NAME="unbound"

configure_certificates
configure_logging
create_configuration
if var_true "${ENABLE_REMOTE_CONTROL}" ; then configure_monitoring; fi;

cat <<EOF

***************************************************************************************
*                                                                                     *
*                    END OF LIFE NOTICE AUGUST 14, 2025                               *
*                               tiredofit/unbound                                     *
*                                                                                     *
* This image is no longer maintained as of and will not receive updates.              *
*                                                                                     *
* A successor image is available at:                                                  *
*                                                                                     *
* Repository | Documentation:                                                         *
*   - https://github.com/nfrastack/container-unbound                                  *
*                                                                                     *
* Image Registries:                                                                   *
*   - https://hub.docker.com/r/nfrastack/unbound                                      *
*   - https://github.com/nfrastack/container-unbound/pkgs/container/container-unbound *
*                                                                                     *
* Please visit https://nfrastack.com for more information.                            *
*                                                                                     *
***************************************************************************************

EOF

sleep 15

liftoff
