#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service single
SERVICE_NAME="unbound"

check_container_initialized
check_service_initialized init
liftoff

print_start "Starting Unbound ${UNBOUND_VERSION/release-/}"
exec unbound \
            -c "${CONFIG_PATH}"/"${CONFIG_FILE}" \
            -d ${UNBOUND_ADDITIONAL_ARGS}
