#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="unbound"
check_container_initialized
check_service_initialized init
liftoff

print_info "Starting Unbound"
exec unbound -d -v
